#!/usr/bin/env bash
# ASCM — One-line Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/gopikomanduri/ascm-poc/main/install.sh | bash
set -euo pipefail

REPO_URL="https://github.com/gopikomanduri/ascm-poc.git"
INSTALL_DIR="${ASCM_DIR:-$HOME/ascm}"
PYTHON="${PYTHON:-python3}"

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[ASCM]${RESET} $*"; }
success() { echo -e "${GREEN}[ASCM]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[ASCM]${RESET} $*"; }
error()   { echo -e "${RED}[ASCM] ERROR:${RESET} $*" >&2; exit 1; }

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║   ASCM — AI Engineering Squad Installer     ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${RESET}"
echo ""

# ── Prerequisites ─────────────────────────────────────────────────────────────
info "Checking prerequisites..."

command -v git    >/dev/null 2>&1 || error "git is required. Install it first: https://git-scm.com"
command -v "$PYTHON" >/dev/null 2>&1 || error "Python 3.11+ is required. Install it first: https://python.org"

PY_VER=$("$PYTHON" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=$("$PYTHON" -c "import sys; print(sys.version_info.major)")
PY_MINOR=$("$PYTHON" -c "import sys; print(sys.version_info.minor)")

if [[ "$PY_MAJOR" -lt 3 ]] || [[ "$PY_MAJOR" -eq 3 && "$PY_MINOR" -lt 11 ]]; then
    error "Python 3.11+ required. Found: $PY_VER"
fi
success "Python $PY_VER ✓"

# ── Clone ─────────────────────────────────────────────────────────────────────
if [[ -d "$INSTALL_DIR/.git" ]]; then
    info "ASCM already cloned at $INSTALL_DIR — pulling latest..."
    git -C "$INSTALL_DIR" pull --quiet origin main
else
    info "Cloning ASCM to $INSTALL_DIR ..."
    git clone --depth=1 --quiet "$REPO_URL" "$INSTALL_DIR"
fi
success "Repository ready ✓"

# ── Virtual environment ───────────────────────────────────────────────────────
info "Creating virtual environment..."
"$PYTHON" -m venv "$INSTALL_DIR/.venv"
VENV_PIP="$INSTALL_DIR/.venv/bin/pip"
VENV_PYTHON="$INSTALL_DIR/.venv/bin/python"
success "Virtual environment created ✓"

# ── Dependencies ──────────────────────────────────────────────────────────────
info "Installing dependencies (this takes ~30 seconds)..."
"$VENV_PIP" install --quiet --upgrade pip
"$VENV_PIP" install --quiet -r "$INSTALL_DIR/requirements.txt"
success "Dependencies installed ✓"

# ── .env setup ────────────────────────────────────────────────────────────────
if [[ ! -f "$INSTALL_DIR/.env" ]]; then
    cp "$INSTALL_DIR/.env.example" "$INSTALL_DIR/.env"
    info "Created $INSTALL_DIR/.env — you need to add your LLM API key."
else
    info ".env already exists — skipping."
fi

# ── Detect existing API key ───────────────────────────────────────────────────
API_KEY_SET=false
if grep -qE "^GEMINI_API_KEY=.+" "$INSTALL_DIR/.env" 2>/dev/null; then API_KEY_SET=true; fi
if grep -qE "^OPENAI_API_KEY=.+" "$INSTALL_DIR/.env" 2>/dev/null; then API_KEY_SET=true; fi
if grep -qE "^ANTHROPIC_API_KEY=.+" "$INSTALL_DIR/.env" 2>/dev/null; then API_KEY_SET=true; fi

# ── Create launcher script ────────────────────────────────────────────────────
LAUNCHER="$HOME/.local/bin/ascm"
mkdir -p "$(dirname "$LAUNCHER")"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# ASCM launcher — generated by install.sh
cd "$INSTALL_DIR"
source .venv/bin/activate
python dashboard_server.py "\$@"
EOF
chmod +x "$LAUNCHER"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════╗${RESET}"
echo -e "${GREEN}${BOLD}║   ✓  ASCM installed successfully!            ║${RESET}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════╝${RESET}"
echo ""

if [[ "$API_KEY_SET" == "false" ]]; then
    echo -e "${YELLOW}${BOLD}Next step: Add your LLM API key${RESET}"
    echo ""
    echo "  Open this file and set GEMINI_API_KEY (or OPENAI_API_KEY):"
    echo -e "  ${CYAN}$INSTALL_DIR/.env${RESET}"
    echo ""
    echo "  Get a free Gemini key at: https://aistudio.google.com/app/apikey"
    echo ""
fi

echo -e "${BOLD}Start ASCM:${RESET}"
echo ""
echo -e "  ${CYAN}# Option 1 — command (if ~/.local/bin is in your PATH):${RESET}"
echo    "  ascm"
echo ""
echo -e "  ${CYAN}# Option 2 — direct:${RESET}"
echo    "  cd $INSTALL_DIR && .venv/bin/python dashboard_server.py"
echo ""
echo -e "  ${CYAN}# Then open:${RESET}"
echo    "  http://localhost:8080/landing"
echo ""
echo -e "  ${CYAN}# Run math proofs (optional):${RESET}"
echo    "  cd $INSTALL_DIR && .venv/bin/python ascm_math_proofs.py"
echo ""
echo -e "Questions? ${CYAN}founders@ascm.dev${RESET} or ${CYAN}github.com/gopikomanduri/ascm-poc/issues${RESET}"
echo ""
